### ISSUE TITLE
User can log in/register with firebase

### ISSUE THREAD

**Issue by Rian501** [nss-day-cohort-20/group-project-movie-history-teambearator#1]
- [x] use google log in
- [x] set up firebase to accept google login credentials
- [ ] change firebase rules to accommodate filtering by user id  in  the data
- [x]  In fb-getter, export module that returns the api key and authDomain
- [x] On fb-config page, require in firebase, set up config object with api key and authDomain, and initialize config
- [ ] use call to firebase to secure click events on the page by verifying user is logged in (conditional)
ex. let currentUser= firebase.auth().currentUser.uid;  if (currentUser){do something}
- [ ] click event for login  using logInGoogle function in user-factory that uses getMovies function in fbMovieFactory to load user movies to the DOM based on userId or loads blank page if user has no saved movies

**Comment by mozecode** [comment]
Please use change tickets for future work.
