### ISSUE TITLE
User can search for new movies in moviedb api  database

### ISSUE THREAD

**Issue by Rian501** [nss-day-cohort-20/group-project-movie-history-teambearator#2]
#Acceptance Criteria
+ **Given** the user wants to search for movies not yet in their collection
+ **When** the user selects "find new movies" and types a search string and hits enter
+ **Then** the api movie database is searched by an ajax call with a query string
+ **And** the results return to the DOM in the form of the movie card
+ **But** any movies already on the watchlist/watched-list will not be printed to the DOM by filtering out IDs we have already
+ **And** the user is able to click "add" to add movie to watch list

- [x] if new movies radio button selected, api call to database based on user string on ENTER
- [x] returns array of objects

- [x] combines the actors list into the movie object to enable display of all needed info

- [x] use template to display in dom

**Comment by mozecode** [comment]
Please use change tickets for future work.
