### ISSUE TITLE
User can search "my movies"

### ISSUE THREAD

**Issue by Rian501** [nss-day-cohort-20/group-project-movie-history-teambearator#3]
#Acceptance Criteria
+ **Given** the user wants to search through their own movie collection (watchlist and watched)
+ **When** the user selects 'search my movies' and types in a search string
+ **Then** the firebase movie list is searched by an ajax call using a regexp
+ **And** the results return to the DOM in the form of the movie cards
+ **And** the user is able to access any card functions (watched/delete)

- [x] make search.js
- [x] iterate over the objects in the firebase collection testing their titles against a regexp (see search function in themepark)
- [ ] print watchlist items according to the watchlist template
- [ ] print watched items according to the watched template, including their star rating if watched and rated

**Comment by mozecode** [comment]
Please use change tickets for future work.
