### ISSUE TITLE
User can view the watchlist

### ISSUE THREAD

**Issue by Rian501** [nss-day-cohort-20/group-project-movie-history-teambearator#4]
#Acceptance Criteria
+ **Given** the user wants to view all their tracked unwatched movies
+ **When** the user clicks "Show Unwatched"
+ **Then** the watchlist movies from firebase are printed to the DOM
+ **And** the user is able to click "watched" to change the category of the movie

- [ ] Listen for click event on the 'show unwatched' button
- [ ] On click, all objects from firebase collection with property "watched": "false" are formatted in the template builder
- [ ] the corresponding movies are printed to the DOM by movie controller

**Comment by mozecode** [comment]
Please use change tickets for future work.
