### ISSUE TITLE
Template / movie cards

### ISSUE THREAD

**Issue by Rian501** [nss-day-cohort-20/group-project-movie-history-teambearator#8]
- [ ] every SAVED movie card gets a DELETE button (when clicked, item removed from FB database)
- [ ] every api-search movie card gets an ADD button which adds the object to FB
- [ ] every WATCHED movie card gets a star rating (clickable) which adjusts the number "rating" on the object
- [ ] every WATCHLIST movie card gets a "watched" button which changes the boolean value from false to true

**Comment by mozecode** [comment]
Please use change tickets for future work.
